In [8]:
#1. Import the NUMPY package under the name np.

import numpy as np


#2. Print the NUMPY version and the configuration.

print(np.__version__)
print(np.show_config())

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))

#4. Print a.
print(a)

1.16.2
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/floratalavera/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/floratalavera/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/floratalavera/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/floratalavera/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/floratalavera/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/floratalavera/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/floratalavera/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/floratalavera/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_r

In [21]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5,2,3))


#6. Print b.
print(b)


#7. Do a and b have the same size? How do you prove that in Python code?

print(a.size)
print(b.size)

if a.size == b.size:
    print(True)

#8. Are you able to add a and b? Why or why not?

print(np.add(a, b))

#a and b cant be added because they don't have the same shapes


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
30
30
True


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [35]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = np.reshape(b, (2,3,5))
print(c)

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = np.add(a, c)


#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(d)


#12. Multiply a and c. Assign the result to e.

e = np.multiply(a, c)
print(e)

#13. Does e equal to a? Why or why not?

#e equal to a because we multiplied the values by 1



[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[1.72601513 1.30171549 1.41275998 1.72218434 1.23857477]
  [1.70717502 1.91097546 1.47782411 1.91988828 1.31691202]
  [1.80997849 1.29893512 1.21290781 1.61379669 1.16903272]]

 [[1.60475664 1.9388052  1.29334758 1.83340397 1.5490442 ]
  [1.73633918 1.76345891 1.33943553 1.16164425 1.58700672]
  [1.60384862 1.2533148  1.70890982 1.44423429 1.19523771]]]
[[[0.72601513 0.30171549 0.41275998 0.72218434 0.23857477]
  [0.70717502 0.91097546 0.47782411 0.91988828 0.31691202]
  [0.80997849 0.29893512 0.21290781 0.61379669 0.16903272]]

 [[0.60475664 0.9388052  0.29334758 0.83340397 0.5490442 ]
  [0.73633918 0.76345891 0.33943553 0.16164425 0.58700672]
  [0.60384862 0.2533148  0.70890982 0.44423429 0.19523771]]]


In [62]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.max(d)
print("The maximum value of d is", d_max)


d_min = np.min(d)
print("The minimum value of d is", d_min)

d_mean = np.mean(d)
print("The mean of d is", d_mean)


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty([2,3,5])
print(f)
#print(d)




The maximum value of d is 1.9388052025213076
The minimum value of d is 1.161644247501045
The mean of d is 1.5283820939726351
[[[1.72601513 1.30171549 1.41275998 1.72218434 1.23857477]
  [1.70717502 1.91097546 1.47782411 1.91988828 1.31691202]
  [1.80997849 1.29893512 1.21290781 1.61379669 1.16903272]]

 [[1.60475664 1.9388052  1.29334758 1.83340397 1.5490442 ]
  [1.73633918 1.76345891 1.33943553 1.16164425 1.58700672]
  [1.60384862 1.2533148  1.70890982 1.44423429 1.19523771]]]


In [82]:

"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""


for i in range(len(d)):
    #print(i)
    for j in range(len(d[0])):
    #print(j)
        for k in range(len(d[0][0])):
            
            value = d[i][j][k]
            #print(value)
        
            if (value > d_min) & (value < d_mean):
                f[i][j][k] = 25
                #assign 25 to the corresponding value in f
                
            elif (value > d_mean) & (value < d_max):
                #print(1)
                f[i][j][k] = 75
                #assign 75 to the corresponding value in f

            elif value == d_mean:
                #print(2)
                f[i][j][k] = 50
                #assign 50 to the corresponding value in f

            elif value == d_min:
                #print(3)
                f[i][j][k] = 0
                #assign 0 to the corresponding value(s) in f

            elif value == d_max:
                #print(4)
                f[i][j][k] = 100
                #assign 100 to the corresponding value(s) in f





[[[ 75.  25.  25.  75.  25.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  25.  25.  75.  25.]]

 [[ 75. 100.  25.  75.  75.]
  [ 75.  75.  25.   0.  75.]
  [ 75.  25.  75.  25.  25.]]]


In [84]:
"""
#17. Print d and f. Do you have your expected f?

For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
        
        
"""

print(d)
print(f)

[[[1.72601513 1.30171549 1.41275998 1.72218434 1.23857477]
  [1.70717502 1.91097546 1.47782411 1.91988828 1.31691202]
  [1.80997849 1.29893512 1.21290781 1.61379669 1.16903272]]

 [[1.60475664 1.9388052  1.29334758 1.83340397 1.5490442 ]
  [1.73633918 1.76345891 1.33943553 1.16164425 1.58700672]
  [1.60384862 1.2533148  1.70890982 1.44423429 1.19523771]]]
[[[ 75.  25.  25.  75.  25.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  25.  25.  75.  25.]]

 [[ 75. 100.  25.  75.  75.]
  [ 75.  75.  25.   0.  75.]
  [ 75.  25.  75.  25.  25.]]]


In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""